---
# tasks file for roles/nginx

- name: upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest

- name: install epel-release
  become: yes
  yum:
    name: epel-release
    state: latest

- name: Disable SELinux
  become: yes
  selinux:
    state: disabled

- name: install nginx
  become: yes
  yum:
    name: nginx
    state: latest

- name: start nginx service
  become: yes
  systemd:
    name: nginx
    state: started

- name: provision the nginx config file
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf


# notify: restarted nginx

