---
# tasks file for roles/node
- name: install nodejs
  become: yes
  package:
    name: nodejs
    state: installed

- name: Install NPM prefix in the app folder
  become: yes
  shell: npm install --prefix /home/todoapp/app