---


- name: message from todoapp
  debug:
    msg: hello from todoapp role

- name: Change of mode of the todoapp folder
  become: yes
  file:
    path: /home/todoapp
    owner: todoapp
    mode: "755"

- name: Change of mode of the app folder
  become: yes
  file:
    path: /home/todoapp/app
    owner: todoapp
    mode: "755"

